server:
  port: 8089

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?useSSL=false&serverTimezone=UTC
    username: root
    password: 123123


mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
